routes/web.php
<?php

// Languages
Route::get('lang/{lang}', function ($lang) {
    session(['lang' => $lang]);
    return \Redirect::back();
})->where([
    'lang' => 'en|es'
    ]);
    
Route::get('/', 'WebController@index');
Route::resource('user', 'UserController');
Route::get('user-verification/{id}', 'UserController@userVerification')->name('user.verification');
# Palcos
Route::resource('box','BoxController');
# Placeas
Route::resource('stall','StallController');
# Foros
Route::get('selectForum','WebController@forums')->name('selectForum');
# Zone
Route::get('selectZone/{id}','WebController@zones')->name('selectZone');
# Foro
Route::get('selectForums/{id}','ForumController@forCountry')->name('selectForums');
# Console Web
Route::get('mi-cuenta','WebController@console')->name('web.console');
Route::resource('property', 'PropertyController');
Route::get('properties/{id}', 'PropertyController@propertyEvents')->name('property.events');
Route::get('propiedades','PropertyController@allProperties')->name('all.properties');
Route::get('propiedades-administradas','PropertyController@admProperties')->name('adm.properties');
#Events in web
Route::get('ver-evento/{id}', 'WebController@eventWeb')->name('event.web');

# Login Facebook

Route::get('auth/{provider}', 'Auth\SocialAuthController@redirectToProvider')->name('social.auth');
Route::get('auth/{provider}/callback', 'Auth\SocialAuthController@handleProviderCallback');
    
Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

#Info
Route::get('info/contacto','WebController@contacto')->name('contacto');
Route::get('info/faq','WebController@faq')->name('faq');
Route::get('info/acerca-de-nosotros','WebController@about')->name('about');
Route::get('info/renta-anual','WebController@renta')->name('renta');
Route::get('info/administracion','WebController@administracion')->name('administracion');
Route::get('info/servicios','WebController@servicios')->name('servicios');
Route::get('info/para-empresas','WebController@empresas')->name('empresas');
Route::get('info/para-propietarios','WebController@propietarios')->name('propietarios');
Route::get('experiencias/vip','WebController@vip')->name('vip');
Route::get('info/terminos-y-condiciones','WebController@terminos')->name('terminos');
Route::get('info/aviso-de-privacidad','WebController@privacidad')->name('privacidad');
Route::get('info/bolsa-de-trabajo','WebController@bolsa')->name('bolsa');
Route::get('info/venta-palcos','WebController@palcos')->name('palcos');


# Console
#Configuracion
Route::get('configuracion', 'ConsoleController@configuration')->name('configuration');
Route::resource('role','RoleController');
Route::resource('systemUser','SystemUserController');
Route::post('home/{home}', 'WebController@update')->name('home.update');
Route::resource('banner','BannerController');;
#Catalogos
Route::get('catalogos', 'ConsoleController@catalogs')->name('catalogs');
Route::resource('country','CountryController');
Route::resource('city','CityController');
Route::resource('amenity','AmenityController');
Route::resource('forum','ForumController');
#Servicios
Route::resource('services','ServiceController');
Route::post('services-snacks','ServiceController@serviceSnacks')->name('services.snacks');
Route::resource('snacks','SnackController');
Route::post('snacks','SnackController@editSnacks')->name('edit.snacks');
#Event
Route::get('eventos', 'ConsoleController@events')->name('events');
Route::resource('evento','EventController')->parameters(['evento'=>'event']);
#Experiences
Route::resource('experiencias','ExperienceController');
Route::post('get-city', 'ExperienceController@getCity')->name('get.city');
Route::post('get-forums', 'ExperienceController@getForums')->name('get.forums');
Route::get('experiences-table', 'ExperienceController@experiencesTable')->name('experiencias.table');
#Package
Route::post('create-package','PackageController@createPackage')->name('create.package');
#Usuarios
Route::get('Usuarios', 'ConsoleController@users')->name('users');
#Reports
Route::resource('reports','ReportController');
#Calendar
Route::get('calendario','CalendarController@index')->name('calendar');
#Coupons
Route::get('cupones','CouponController@index')->name('coupons');
#Job Exchange
Route::get('bolsa-de-trabajo','JobExchangeController@index')->name('job.exchange.index');
Route::post('job-exchange-email','JobExchangeController@jobExchangeEmail')->name('job.exchange.email');

app/Http/Controllers/ConsoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Home;
use App\Models\Banner;

class ConsoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function configuration()
    {
        $banner = Banner::orderBy('position','ASC')->get();;
        $home = Home::first();
        $home->tab = explode(';', $home->tab);
        
        return view('console.configuration.index',compact('home','banner'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function catalogs()
    {   
        return view('console.catalogs.index');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function events()
    {        
        return view('console.event.index');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function users()
    {        
        return view('console.user.index');
    }
}

resources/views/console/includes/aside.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{asset('console/dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>Diego Kawas</p>
            </div>
        </div>
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">NAVEGACIÓN</li>
            <li class="">
                <a href="index.php">
                    <i class="fa fa-dashboard"></i> <span>Tablero</span>
                </a>
            </li>
            <li>
                <a href="{!!route('events')!!}">
                    <i class="fa fa-futbol-o"></i>
                    <span>Eventos</span>
                </a>
            </li>
            <li>
                <a href="{{route('reports.index')}}">
                    <i class="fa fa-file-text"></i> <span>Reportes/Transacciones</span>
                </a>
            </li>
            <li>
                <a href="{!!route('users')!!}">
                    <i class="fa fa-user"></i>
                    <span>Usuarios</span>
                </a>
            </li>
            <li>
                <a href="renta_anual.php">
                    <i class="fa fa-bars"></i>
                    <span>Renta Anual</span>
                </a>
            </li>
            <li>
                <a href="{!! route('experiencias.index') !!}">
                    <i class="fa fa-star"></i>
                    <span>Experiencias</span>
                </a>
            </li>
            <li class="treeview menu">
                <a href="#">
                    <i class="fa fa-home"></i>
                    <span>Propiedades</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                    <ul class="treeview-menu">
                        <li><a href="{{route('all.properties')}}"><i class="fa fa-circle-o"></i> Todas</a></li>
                        <li><a href="{{route('adm.properties')}}"><i class="fa fa-circle-o"></i> Administradas</a></li>
                    </ul>
                </a>
            </li>
            <li class="treeview menu">
                <a href="#">
                    <i class="fa fa-motorcycle"></i>
                    <span>Logística</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                    <ul class="treeview-menu">
                        <li><a href="logistica.html"><i class="fa fa-circle-o"></i> En Curso</a></li>
                        <li><a href="logistica_cierre.html"><i class="fa fa-circle-o"></i> Cierre del Día</a></li>
                        <li><a href="logistica_historial.html"><i class="fa fa-circle-o"></i> Historial</a></li>
                    </ul>
                </a>
            </li>
            <li>
                <a href="{{route('catalogs')}}">
                    <i class="fa fa-book"></i> <span>Catálogos</span>
                </a>
            </li>
            <li>
                <a href="{{route('calendar')}}">
                    <i class="fa fa-calendar"></i> <span>Calendario</span>
                    <span class="pull-right-container">
                        <small class="label pull-right bg-red">3</small>
                    </span>
                </a>
            </li>
            <li>
                <a href="{{route('coupons')}}">
                    <i class="fa fa-ticket"></i>
                    <span>Cupones</span>
                </a>
            </li>
            <li><a href="{{route('configuration')}}"><i class="fa fa-cog"></i> <span>Configuración</span></a></li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

resources/views/console/includes/footer.blade.php
<!-- FOOTER wrapper -->
<footer class="main-footer">
	<div class="pull-right hidden-xs">
	    <b>Stadibox</b> 1.1
	</div>
	<strong>Stadibox &copy; 2018.</strong> Powered by: <a href="https://www.bluepixel.mx">BluePixel</a>
</footer>

resources/views/console/includes/head.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Stadibox | @yield('title')</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{ asset('console/bootstrap/dist/css/bootstrap.min.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('console/font-awesome/css/font-awesome.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset('console/Ionicons/css/ionicons.min.css') }}">
    <!-- fullCalendar -->
    <link rel="stylesheet" href="{{ asset('console/fullcalendar/dist/fullcalendar.min.css') }}">
    <link rel="stylesheet" href="{{ asset('console/fullcalendar/dist/fullcalendar.print.min.css') }}" media="print">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('console/dist/css/AdminLTE.min.css') }}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ asset('console/dist/css/skins/_all-skins.min.css') }}">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{{ asset('console/morris.js/morris.css') }}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{ asset('console/jvectormap/jquery-jvectormap.css') }}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{{ asset('console/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{ asset('console/bootstrap-daterangepicker/daterangepicker.css') }}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{{ asset('console/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">
    <!-- bootstrap toggle --> 
    <link href="{{ asset('console/bootstrap-toggle-master/css/bootstrap-toggle.css') }}" rel="stylesheet">
    <!-- Select2 -->
    <link rel="stylesheet" href="{{asset('console/select2/dist/css/select2.min.css')}}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <!-- CSFR token for ajax call -->
    <meta name="_token" content="{{ csrf_token() }}"/>
    <!-- Bootstrap Color Picker -->
    <link rel="stylesheet" href="{{asset('console/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css')}}">
    <!-- Bootstrap time Picker -->
    <link rel="stylesheet" href="{{asset('console/plugins/timepicker/bootstrap-timepicker.min.css')}}">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="{{asset('console/plugins/iCheck/all.css')}}">
    <!-- DataTables -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <!-- bootstrap slider -->
    <link rel="stylesheet" href="{{asset('console/plugins/bootstrap-slider/slider.css')}}">
    @yield('css')
</head>

resources/views/console/includes/header.blade.php
<header class="main-header">
  <!-- Logo -->
  <a href="{{url('/')}}" target="_blank" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>S</b>B</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Stadibox</b> Admin</span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- Messages: style can be found in dropdown.less-->
        <li class="dropdown messages-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-envelope-o"></i>
            <span class="label label-success">4</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">Tienes 4 mensajes</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                <li><!-- start message -->
                  <a href="#">
                    <div class="pull-left">
                      <img src="{{asset('console/dist/img/user2-160x160.jpg')}}" class="img-  circle" alt="User Image">
                    </div>
                    <h4>
                      Equipo de Soporte
                      <small><i class="fa fa-clock-o"></i> 5 mins</small>
                    </h4>
                    <p>Hay que subir imágenes del sitio</p>
                  </a>
                </li>
                <!-- end message -->
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="{{asset('console/dist/img/user3-128x128.jpg')}}" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                      Israel Baca
                      <small><i class="fa fa-clock-o"></i> 2 hours</small>
                    </h4>
                    <p>Checar nuevos palcos</p>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="{{asset('console/dist/img/user4-128x128.jpg')}}" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                      Diseñadores
                      <small><i class="fa fa-clock-o"></i> Today</small>
                    </h4>
                    <p>Están listas las imágenes!</p>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="{{asset('console/dist/img/user3-128x128.jpg')}}" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                      Usuario #33019
                      <small><i class="fa fa-clock-o"></i> Yesterday</small>
                    </h4>
                    <p>Necesito ayuda.</p>
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer">
              <a href="#">Ver todos los mensajes</a>
            </li>
          </ul>
        </li>
        <!-- Notifications: style can be found in dropdown.less -->
        <li class="dropdown notifications-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell-o"></i>
            <span class="label label-warning">10</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">Tienes 10 notificaciones</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                <li>
                  <a href="#">
                    <i class="fa fa-users text-aqua"></i> 5 personas se registraron hoy
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-warning text-yellow"></i> Así se verá una notificación con mucho texto que no se verá completa
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-users text-red"></i> 5 personas se unieron
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-shopping-cart text-green"></i> 25 ventas hechas
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-user text-red"></i> Cambiaste tu nombre de usuario
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer"><a href="#">Ver todas</a></li>
          </ul>
        </li>
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="{{asset('console/dist/img/user2-160x160.jpg')}}" class="user-image" alt="User Image">
            <span class="hidden-xs">Diego Kawas</span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <img src="{{asset('console/dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">

              <p>
                Diego Kawas - Administrador
                <small>Miembro desde: Marzo 2018</small>
              </p>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Perfil</a>
              </div>
              <div class="pull-right">
                <a href="#" class="btn btn-default btn-flat">Cerrar Sesión</a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

resources/views/console/includes/scripts.blade.php
<!-- jQuery 3 -->
<script src="{{asset('console/jquery/dist/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('console/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('console/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<!-- Select2 -->
<script src="{{asset('console/select2/dist/js/select2.full.min.js')}}"></script>
<!-- InputMask -->
<script src="{{asset('console/plugins/input-mask/jquery.inputmask.js')}}"></script>
<script src="{{asset('console/plugins/input-mask/jquery.inputmask.date.extensions.js')}}"></script>
<script src="{{asset('console/plugins/input-mask/jquery.inputmask.extensions.js')}}"></script>
<!-- Morris.js charts -->
<script src="{{asset('console/raphael/raphael.min.js')}}"></script>
<script src="{{asset('console/morris.js/morris.min.js')}}"></script>
<!-- Sparkline -->
<script src="{{asset('console/jquery-sparkline/dist/jquery.sparkline.min.js')}}"></script>
<!-- jvectormap -->
<script src="{{asset('console/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js')}}"></script>
<script src="{{asset('console/plugins/jvectormap/jquery-jvectormap-world-mill-en.js')}}"></script>
<!-- jQuery Knob Chart -->
<script src="{{asset('console/jquery-knob/dist/jquery.knob.min.js')}}"></script>
<!-- daterangepicker -->
<script src="{{asset('console/moment/min/moment.min.js')}}"></script>
<script src="{{asset('console/bootstrap-daterangepicker/daterangepicker.js')}}"></script>
<!-- datepicker -->
<!-- bootstrap color picker -->
<script src="{{asset('console/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js')}}"></script>
<script src="{{asset('console/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')}}"></script>
<!-- bootstrap time picker -->
<script src="{{asset('console/plugins/timepicker/bootstrap-timepicker.min.js')}}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{asset('console/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js')}}"></script>
<!-- Slimscroll -->
<script src="{{asset('console/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
<!-- iCheck 1.0.1 -->
<script src="{{asset('console/plugins/iCheck/icheck.min.js')}}"></script>
<!-- FastClick -->
<script src="{{asset('console/fastclick/lib/fastclick.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('console/dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{asset('console/dist/js/pages/dashboard.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('console/dist/js/demo.js')}}"></script>
<!-- Bootstrap slider -->
<script src="{{asset('console/plugins/bootstrap-slider/bootstrap-slider.js')}}"></script>
<!-- Bootstrap Toggle -->
<script src="{{asset('console/bootstrap-toggle-master/js/bootstrap-toggle.js')}}"></script>
<!-- DataTables -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<!-- fullCalendar -->
<script src="{{ asset('console/fullcalendar/dist/fullcalendar.min.js') }}"></script>
<!--Country Select-->
<script type="text/javascript">
	//Country
	$(document).ready(function() {
		//-------------------------------SELECT CASCADING-------------------------//
		var selectedCountry = (selectedRegion = selectedCity = countryCode = "");

		// This is a demo API key for testing purposes. You should rather request your API key (free) from http://battuta.medunes.net/
		var BATTUTA_KEY = "00000000000000000000000000000000";
		// Populate country select box from battuta API
		url =
		"https://battuta.medunes.net/api/country/all/?key=" +
		BATTUTA_KEY +
		"&callback=?";

		// EXTRACT JSON DATA.
		$.getJSON(url, function(data) {
			$.each(data, function(index, value) {
			  // APPEND OR INSERT DATA TO SELECT ELEMENT. Set the country code in the id section rather than in the value.
			  $(".country").append(
			    '<option id="' +
			      value.code +
			      '" value="' +
			      value.name +
			      '">' +
			      value.name +
			      "</option>"
			  );
			});
		});
		// Country selected --> update region list .
		$(".country").change(function() {
			selectedCountry = this.options[this.selectedIndex].text;
			// get the id of the option which has the country code.
			countryCode = $(this)
			  .children(":selected")
			  .attr("id");
			// Populate country select box from battuta API
			url =
			  "https://battuta.medunes.net/api/region/" +
			  countryCode +
			  "/all/?key=" +
			  BATTUTA_KEY +
			  "&callback=?";
			$.getJSON(url, function(data) {
			  $(".region option").remove();
			  $('.region').append('<option>Ciudad</option>');
			  $.each(data, function(index, value) {
			    // APPEND OR INSERT DATA TO SELECT ELEMENT.
			    $(".region").append(
			      '<option value="' + value.region + '">' + value.region + "</option>"
			    );
			  });
			});
		});
		// Region selected --> updated city list
		$("#region").on("change", function() {
		selectedRegion = this.options[this.selectedIndex].text;
		// Populate country select box from battuta API
		// countryCode = $("#country").val();
		region = $("#region").val();
		url =
		  "https://battuta.medunes.net/api/city/" +
		  countryCode +
		  "/search/?region=" +
		  region +
		  "&key=" +
		  BATTUTA_KEY +
		  "&callback=?";
		$.getJSON(url, function(data) {
		  console.log(data);
		  $("#city option").remove();
		  $('#city').append('<option value="">Please select your city</option>');
		  $.each(data, function(index, value) {
		    // APPEND OR INSERT DATA TO SELECT ELEMENT.
		    $("#city").append(
		      '<option value="' + value.city + '">' + value.city + "</option>"
		    );
		  });
		});
	  });
	  // city selected --> update location string
	  $("#city").on("change", function() {
	    selectedCity = this.options[this.selectedIndex].text;
	    $("#location").html(
	      "Locatation: Country: " +
	        selectedCountry +
	        ", Region: " +
	        selectedRegion +
	        ", City: " +
	        selectedCity
	    );
	  });
	});
</script>
<!--Selects-->
<script type="text/javascript">
	// Role
    $(function(){
        $.ajax({
            type: "GET",
            url: '{{ route('role.index') }}', 
            dataType: "json",
            success: function(data){
                $.each(data['data'],function(key, registro) {
                    $('#role_id').append('<option value='+registro.id+'>'+registro.name+'</option>');
                    $('#edit_role_id').append('<option value='+registro.id+'>'+registro.name+'</option>');
                });        
            },
            error: function(data) {
                alert('¡ERROR! cargando Perfiles contacte al soporte tecnico');
            }
        });
    })
</script>
@yield('js')